"""
payout_filter.py - Mathematical Expectation & Wilson Score Lower Bound Filter.

Formulations:
1. Break-Even Probability:
   P_BE = 1 / (1 + Payout)

2. Exact Closed-Form Wilson Score Interval Lower Bound (95% confidence, z = 1.96):
   WLB = (p_hat + z^2 / (2n) - z * sqrt(p_hat * (1 - p_hat) / n + z^2 / (4n^2))) / (1 + z^2 / n)

3. Conservative Expected Value:
   EV_WLB = WLB * (1 + Payout) - 1

4. Strict Execution Invariant:
   execute_trade iff EV_WLB > 0 (strictly equivalent to WLB > P_BE).
   Guarantees that small samples and lucky streaks cannot pass the filter.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional
import numpy as np


@dataclass(frozen=True)
class TradeGateDecision:
    """Execution decision generated by the payout and statistical expectation gate."""
    allow_trade: bool
    wlb: float
    p_be: float
    ev_wlb: float
    nominal_ev: float
    p_hat: float
    sample_n: int
    rejection_reason: Optional[str] = None


def compute_payout_be(payout: float) -> float:
    """
    Computes exact Break-Even win rate for binary options:
    P_BE = 1 / (1 + payout)
    
    Examples:
    - Payout 0.85 (85%) -> P_BE = 1 / 1.85 ~ 0.54054 (54.05%)
    - Payout 0.70 (70%) -> P_BE = 1 / 1.70 ~ 0.58824 (58.82%)
    - Payout 0.90 (90%) -> P_BE = 1 / 1.90 ~ 0.52632 (52.63%)
    """
    if payout <= 0.0:
        return 1.0
    return float(1.0 / (1.0 + payout))


# Alias for spec compliance
compute_payout_breakeven = compute_payout_be
calculate_p_be = compute_payout_be


def compute_wilson_lower_bound(p_hat: float, n: int, z: float = 1.96) -> float:
    """
    Computes exact closed-form Wilson Score Interval Lower Bound (Wilson, 1927).
    
    Args:
        p_hat: Observed sample success proportion (wins / n).
        n: Total sample size (trades).
        z: Standard normal quantile (default 1.96 for two-sided 95% confidence).
        
    Returns:
        WLB in [0.0, 1.0].
    """
    if n <= 0:
        return 0.0

    p_hat = float(max(0.0, min(1.0, p_hat)))
    z2 = z * z
    n_float = float(n)

    denominator = 1.0 + (z2 / n_float)
    center = p_hat + (z2 / (2.0 * n_float))
    radicand = (p_hat * (1.0 - p_hat) / n_float) + (z2 / (4.0 * n_float * n_float))
    
    # Numerical safeguard against tiny negative floating point values
    spread = z * np.sqrt(max(0.0, radicand))
    
    wlb = (center - spread) / denominator
    return float(max(0.0, min(1.0, wlb)))


# Alias for spec compliance
wilson_lower_bound = compute_wilson_lower_bound



def compute_expected_value(win_rate: float, payout: float) -> float:
    """
    Computes normalized Expected Value per unit risked:
    EV = win_rate * payout - (1 - win_rate) = win_rate * (1 + payout) - 1
    """
    return float(win_rate * (1.0 + payout) - 1.0)


def evaluate_trade_gate(
    sample_wins: int,
    sample_n: int,
    payout: float,
    z: float = 1.96,
) -> TradeGateDecision:
    """
    Interface contract function matching PROJECT.md:
    evaluate_trade_gate(sample_wins: int, sample_n: int, payout: float) -> TradeGateDecision
    
    Enforces the invariant execution gate:
    allowed = (EV_WLB > 0.0) <==> (WLB > P_BE)
    """
    if sample_n <= 0:
        p_be = compute_payout_be(payout)
        return TradeGateDecision(
            allow_trade=False,
            wlb=0.0,
            p_be=p_be,
            ev_wlb=-1.0,
            nominal_ev=-1.0,
            p_hat=0.0,
            sample_n=0,
            rejection_reason="No sample history available (n=0)",
        )

    p_hat = float(sample_wins) / float(sample_n)
    p_be = compute_payout_be(payout)
    wlb = compute_wilson_lower_bound(p_hat=p_hat, n=sample_n, z=z)
    
    nominal_ev = compute_expected_value(win_rate=p_hat, payout=payout)
    ev_wlb = compute_expected_value(win_rate=wlb, payout=payout)

    # Invariant: EV_WLB > 0.0 (equivalently WLB > P_BE)
    if ev_wlb > 0.0 and wlb > p_be:
        return TradeGateDecision(
            allow_trade=True,
            wlb=wlb,
            p_be=p_be,
            ev_wlb=ev_wlb,
            nominal_ev=nominal_ev,
            p_hat=p_hat,
            sample_n=sample_n,
            rejection_reason=None,
        )
    else:
        reason = (
            f"Insufficient statistical edge after payout: "
            f"EV_WLB ({ev_wlb:.4f}) <= 0 or WLB ({wlb:.4f}) <= P_BE ({p_be:.4f}) "
            f"[sample: {sample_wins}/{sample_n} = {p_hat*100:.1f}%]"
        )
        return TradeGateDecision(
            allow_trade=False,
            wlb=wlb,
            p_be=p_be,
            ev_wlb=ev_wlb,
            nominal_ev=nominal_ev,
            p_hat=p_hat,
            sample_n=sample_n,
            rejection_reason=reason,
        )


def evaluate_payout_gate(
    payout: float,
    sample_winrate: float,
    sample_trades: int,
    z: float = 1.96,
) -> TradeGateDecision:
    """
    Alternative convenience function accepting float winrate and trade count.
    """
    wins = int(round(sample_winrate * sample_trades))
    return evaluate_trade_gate(
        sample_wins=wins,
        sample_n=sample_trades,
        payout=payout,
        z=z,
    )
